"""The question bank's starting set (English).

Loaded once by migration 0154; after that the bank lives in the database and
is edited in the Django admin. Every answer is checked against the KJV text
it cites. `answer` is the index of the right choice as written here — choices
are shuffled each time a question is asked.
"""

TRUE_FALSE = ['True', 'False']

SEED = [
    # ── Who said this ─────────────────────────────────────────────────────────
    dict(kind='who_said', difficulty='moderate', category='major_prophets',
         prompt='Who said, "Here am I; send me"?',
         choices=['Isaiah', 'Jeremiah', 'Samuel', 'Moses'], answer=0,
         explanation='Isaiah answered the Lord\'s call after his vision in the temple.',
         reference='Isaiah 6:8'),
    dict(kind='who_said', difficulty='simple', category='history',
         prompt='Who said, "Whither thou goest, I will go"?',
         choices=['Ruth', 'Naomi', 'Orpah', 'Esther'], answer=0,
         explanation='Ruth said it to her mother-in-law Naomi, choosing Naomi\'s people and God.',
         reference='Ruth 1:16'),
    dict(kind='who_said', difficulty='simple', category='history',
         prompt='Who said, "As for me and my house, we will serve the LORD"?',
         choices=['Joshua', 'Moses', 'Caleb', 'David'], answer=0,
         explanation='Joshua said it to all Israel gathered at Shechem.',
         reference='Joshua 24:15'),
    dict(kind='who_said', difficulty='simple', category='gospels',
         prompt='Who said, "Thou art the Christ, the Son of the living God"?',
         choices=['Peter', 'John', 'Andrew', 'Thomas'], answer=0,
         explanation='Peter answered when Jesus asked, "But whom say ye that I am?"',
         reference='Matthew 16:16'),
    dict(kind='who_said', difficulty='moderate', category='gospels',
         prompt='Who said, "My Lord and my God"?',
         choices=['Thomas', 'Peter', 'Mary Magdalene', 'Nathanael'], answer=0,
         explanation='Thomas said it when the risen Jesus showed him his hands and side.',
         reference='John 20:28'),
    dict(kind='who_said', difficulty='moderate', category='wisdom',
         prompt='Who said, "I know that my redeemer liveth"?',
         choices=['Job', 'David', 'Isaiah', 'Jeremiah'], answer=0,
         explanation='Job said it in the depth of his suffering.',
         reference='Job 19:25'),
    dict(kind='who_said', difficulty='moderate', category='history',
         prompt='Who said, "Speak; for thy servant heareth"?',
         choices=['Samuel', 'Eli', 'Elijah', 'Gideon'], answer=0,
         explanation='The boy Samuel answered the Lord\'s call in the night, as Eli had told him to.',
         reference='1 Samuel 3:10'),
    dict(kind='who_said', difficulty='simple', category='law',
         prompt='Who asked, "Am I my brother\'s keeper?"',
         choices=['Cain', 'Abel', 'Esau', 'Jacob'], answer=0,
         explanation='Cain answered the Lord with this question after killing Abel.',
         reference='Genesis 4:9'),
    dict(kind='who_said', difficulty='moderate', category='history',
         prompt='Who said, "If I perish, I perish"?',
         choices=['Esther', 'Ruth', 'Deborah', 'Abigail'], answer=0,
         explanation='Esther said it before going to the king unbidden to plead for her people.',
         reference='Esther 4:16'),
    dict(kind='who_said', difficulty='hard', category='acts',
         prompt='Who said to Paul, "Almost thou persuadest me to be a Christian"?',
         choices=['King Agrippa', 'Felix', 'Festus', 'Gallio'], answer=0,
         explanation='King Agrippa said it after hearing Paul\'s defence.',
         reference='Acts 26:28'),
    dict(kind='who_said', difficulty='moderate', category='gospels',
         prompt='Who asked Jesus, "What is truth?"',
         choices=['Pilate', 'Herod', 'Caiaphas', 'Annas'], answer=0,
         explanation='Pilate asked it during Jesus\' trial.',
         reference='John 18:38'),
    dict(kind='who_said', difficulty='moderate', category='gospels',
         prompt='Who said, "Lord, remember me when thou comest into thy kingdom"?',
         choices=['A thief crucified with Jesus', 'Joseph of Arimathea', 'Nicodemus', 'The centurion'], answer=0,
         explanation='One of the two thieves crucified with Jesus asked it; Jesus promised him paradise.',
         reference='Luke 23:42'),
    dict(kind='who_said', difficulty='simple', category='epistles',
         prompt='Who wrote, "I have fought a good fight, I have finished my course"?',
         choices=['Paul', 'Peter', 'Timothy', 'Stephen'], answer=0,
         explanation='Paul wrote it to Timothy near the end of his life.',
         reference='2 Timothy 4:7'),
    dict(kind='who_said', difficulty='simple', category='gospels',
         prompt='Who said, "Behold the Lamb of God, which taketh away the sin of the world"?',
         choices=['John the Baptist', 'Andrew', 'Peter', 'Simeon'], answer=0,
         explanation='John the Baptist said it when he saw Jesus coming to him.',
         reference='John 1:29'),
    dict(kind='who_said', difficulty='hard', category='gospels',
         prompt='Who said, "Lord, now lettest thou thy servant depart in peace"?',
         choices=['Simeon', 'Zacharias', 'Joseph', 'Anna'], answer=0,
         explanation='Simeon said it in the temple, holding the child Jesus.',
         reference='Luke 2:29'),
    dict(kind='who_said', difficulty='moderate', category='wisdom',
         prompt='Who said, "The LORD gave, and the LORD hath taken away"?',
         choices=['Job', 'Naomi', 'Eli', 'David'], answer=0,
         explanation='Job said it after losing his children and possessions in a single day.',
         reference='Job 1:21'),
    dict(kind='who_said', difficulty='moderate', category='wisdom',
         prompt='Who prayed, "Create in me a clean heart, O God"?',
         choices=['David', 'Solomon', 'Asaph', 'Moses'], answer=0,
         explanation='David prayed it in Psalm 51, after Nathan confronted him.',
         reference='Psalms 51:10'),

    # ── True or false ─────────────────────────────────────────────────────────
    dict(kind='true_false', difficulty='simple', category='minor_prophets',
         prompt='True or false: Jonah was in the belly of the fish three days and three nights.',
         choices=TRUE_FALSE, answer=0,
         explanation='The Lord prepared a great fish, and Jonah was in it three days and three nights.',
         reference='Jonah 1:17'),
    dict(kind='true_false', difficulty='simple', category='history',
         prompt='True or false: Moses led Israel across the Jordan into Canaan.',
         choices=TRUE_FALSE, answer=1,
         explanation='Moses died before the crossing; Joshua led Israel over the Jordan.',
         reference='Joshua 3:17'),
    dict(kind='true_false', difficulty='simple', category='gospels',
         prompt='True or false: Jesus was born in Nazareth.',
         choices=TRUE_FALSE, answer=1,
         explanation='Jesus was born in Bethlehem of Judaea, and grew up in Nazareth.',
         reference='Matthew 2:1'),
    dict(kind='true_false', difficulty='simple', category='acts',
         prompt='True or false: Saul met the risen Jesus on the road to Damascus.',
         choices=TRUE_FALSE, answer=0,
         explanation='A light from heaven shone round him as he came near Damascus.',
         reference='Acts 9:3'),
    dict(kind='true_false', difficulty='moderate', category='major_prophets',
         prompt='True or false: Daniel was thrown into a fiery furnace.',
         choices=TRUE_FALSE, answer=1,
         explanation='Daniel was cast into the lions\' den; his three friends were cast into the furnace.',
         reference='Daniel 6:16'),
    dict(kind='true_false', difficulty='hard', category='history',
         prompt='True or false: The book of Esther never mentions God by name.',
         choices=TRUE_FALSE, answer=0,
         explanation='God is not named in Esther, though his care for his people runs through it.',
         reference='Esther 4:14'),
    dict(kind='true_false', difficulty='moderate', category='history',
         prompt='True or false: Elijah went up by a whirlwind into heaven.',
         choices=TRUE_FALSE, answer=0,
         explanation='A chariot of fire parted Elijah and Elisha, and Elijah went up by a whirlwind.',
         reference='2 Kings 2:11'),
    dict(kind='true_false', difficulty='moderate', category='gospels',
         prompt='True or false: The Sermon on the Mount is in the Gospel of John.',
         choices=TRUE_FALSE, answer=1,
         explanation='The Sermon on the Mount is in Matthew, chapters 5 to 7.',
         reference='Matthew 5:1'),
    dict(kind='true_false', difficulty='simple', category='gospels',
         prompt='True or false: Lazarus was the brother of Mary and Martha.',
         choices=TRUE_FALSE, answer=0,
         explanation='Lazarus of Bethany was the brother of Mary and Martha.',
         reference='John 11:1'),
    dict(kind='true_false', difficulty='hard', category='law',
         prompt='True or false: Noah sent out both a raven and a dove from the ark.',
         choices=TRUE_FALSE, answer=0,
         explanation='Noah first sent forth a raven, then a dove.',
         reference='Genesis 8:7'),

    # ── Which came first ──────────────────────────────────────────────────────
    dict(kind='order', difficulty='simple', category='law',
         prompt='Which came first?',
         choices=['The flood', 'The tower of Babel', 'The call of Abram', 'The exodus from Egypt'], answer=0,
         explanation='The flood (Genesis 7) came before Babel (11), Abram\'s call (12) and the exodus.',
         reference='Genesis 7:17'),
    dict(kind='order', difficulty='moderate', category='law',
         prompt='Which happened first?',
         choices=['Joseph sold into Egypt', 'Moses at the burning bush', 'David anointed king', 'The fall of Jericho'], answer=0,
         explanation='Joseph was sold into Egypt generations before Moses, Jericho or David.',
         reference='Genesis 37:28'),
    dict(kind='order', difficulty='simple', category='history',
         prompt='Which king reigned first?',
         choices=['Saul', 'David', 'Solomon', 'Rehoboam'], answer=0,
         explanation='Saul was Israel\'s first king, then David, then Solomon, then Rehoboam.',
         reference='1 Samuel 10:1'),
    dict(kind='order', difficulty='moderate', category='gospels',
         prompt='Which happened first in Jesus\' ministry?',
         choices=['His baptism', 'The feeding of the five thousand', 'The transfiguration', 'The triumphal entry'], answer=0,
         explanation='Jesus was baptised by John before his ministry began.',
         reference='Matthew 3:16'),
    dict(kind='order', difficulty='moderate', category='acts',
         prompt='Which came first in the book of Acts?',
         choices=['Pentecost', 'The stoning of Stephen', 'The conversion of Saul', 'The council at Jerusalem'], answer=0,
         explanation='Pentecost is in Acts 2; Stephen in 7, Saul in 9, the council in 15.',
         reference='Acts 2:1'),
    dict(kind='order', difficulty='hard', category='history',
         prompt='Which prophet came first?',
         choices=['Elijah', 'Isaiah', 'Daniel', 'Malachi'], answer=0,
         explanation='Elijah served in Ahab\'s day, before Isaiah, Daniel and Malachi.',
         reference='1 Kings 17:1'),

    # ── Bible facts ───────────────────────────────────────────────────────────
    dict(kind='fact', difficulty='simple', category='',
         prompt='How many books are in the Bible?',
         choices=['66', '39', '27', '73'], answer=0,
         explanation='39 in the Old Testament and 27 in the New.', reference=''),
    dict(kind='fact', difficulty='simple', category='law',
         prompt='Who built the ark?',
         choices=['Noah', 'Moses', 'Abraham', 'Lot'], answer=0,
         explanation='God told Noah to make an ark of gopher wood.', reference='Genesis 6:14'),
    dict(kind='fact', difficulty='simple', category='gospels',
         prompt='Where was Jesus crucified?',
         choices=['Golgotha', 'Gethsemane', 'Bethany', 'The Mount of Olives'], answer=0,
         explanation='Golgotha, the place of a skull.', reference='John 19:17'),
    dict(kind='fact', difficulty='simple', category='minor_prophets',
         prompt='Which prophet fled from God\'s call to preach to Nineveh?',
         choices=['Jonah', 'Amos', 'Hosea', 'Micah'], answer=0,
         explanation='Jonah went down to Joppa and took a ship to Tarshish.', reference='Jonah 1:3'),
    dict(kind='fact', difficulty='simple', category='gospels',
         prompt='How many apostles did Jesus choose?',
         choices=['Twelve', 'Seven', 'Seventy', 'Ten'], answer=0,
         explanation='He ordained twelve, that they should be with him.', reference='Mark 3:14'),
    dict(kind='fact', difficulty='moderate', category='law',
         prompt='What was the first plague on Egypt?',
         choices=['Water turned to blood', 'Frogs', 'Lice', 'Darkness'], answer=0,
         explanation='Aaron struck the river, and the waters were turned to blood.', reference='Exodus 7:20'),
    dict(kind='fact', difficulty='moderate', category='history',
         prompt='Who was the mother of Samuel?',
         choices=['Hannah', 'Elisabeth', 'Sarah', 'Rachel'], answer=0,
         explanation='Hannah prayed for a son and named him Samuel.', reference='1 Samuel 1:20'),
    dict(kind='fact', difficulty='simple', category='law',
         prompt='On which day did God rest from all his work of creation?',
         choices=['The seventh day', 'The sixth day', 'The first day', 'The eighth day'], answer=0,
         explanation='On the seventh day God ended his work, and he rested.', reference='Genesis 2:2'),
    dict(kind='fact', difficulty='simple', category='epistles',
         prompt='Who wrote most of the letters in the New Testament?',
         choices=['Paul', 'Peter', 'John', 'James'], answer=0,
         explanation='Thirteen of the letters open with Paul\'s name.', reference='Romans 1:1'),
    dict(kind='fact', difficulty='simple', category='gospels',
         prompt='What did Jesus turn water into at the wedding in Cana?',
         choices=['Wine', 'Oil', 'Milk', 'Vinegar'], answer=0,
         explanation='It was his first miracle.', reference='John 2:9'),
    dict(kind='fact', difficulty='moderate', category='major_prophets',
         prompt='Who told Nebuchadnezzar his dream and its meaning?',
         choices=['Daniel', 'Joseph', 'Ezekiel', 'Jeremiah'], answer=0,
         explanation='The secret was revealed to Daniel in a night vision.', reference='Daniel 2:19'),
]
