"""The question bank's second set: more English, and the first Swahili.

Loaded once by migration 0180 — a question already in the bank (the same
prompt in the same language) is left as it is, so an admin's edits are never
undone. `answer` is the index of the right choice as written here; choices
are shuffled each time a question is asked (true/false keeps its order).

The Swahili names follow the Swahili Bible (Musa, Yusufu, Daudi, Petro);
references use its book names (Mwanzo, Kutoka, Mathayo).
"""

TRUE_FALSE = ['True', 'False']
KWELI = ['Kweli', 'Si kweli']

SEED_EN = [
    # ── Who said this ─────────────────────────────────────────────────────────
    dict(kind='who_said', difficulty='moderate', category='law',
         prompt='Who said to Pharaoh, "Let my people go"?',
         choices=['Moses', 'Joshua', 'Joseph', 'Elijah'], answer=0,
         explanation='Moses and Aaron brought the LORD\'s word to Pharaoh.', reference='Exodus 5:1'),
    dict(kind='who_said', difficulty='simple', category='gospels',
         prompt='Who prayed, "Not my will, but thine, be done"?',
         choices=['Jesus', 'Peter', 'Paul', 'Stephen'], answer=0,
         explanation='Jesus prayed it on the Mount of Olives the night he was betrayed.', reference='Luke 22:42'),
    dict(kind='who_said', difficulty='moderate', category='history',
         prompt='Who said, "Is there not a cause?" before facing Goliath?',
         choices=['David', 'Jonathan', 'Saul', 'Eliab'], answer=0,
         explanation='David answered his brother Eliab, who had scolded him.', reference='1 Samuel 17:29'),
    dict(kind='who_said', difficulty='moderate', category='gospels',
         prompt='Who said, "He must increase, but I must decrease"?',
         choices=['John the Baptist', 'Peter', 'Andrew', 'Nicodemus'], answer=0,
         explanation='John the Baptist said it of Jesus, when his own disciples worried that all were going to Jesus.',
         reference='John 3:30'),
    dict(kind='who_said', difficulty='moderate', category='acts',
         prompt='Who said, "Silver and gold have I none; but such as I have give I thee"?',
         choices=['Peter', 'John', 'Paul', 'Barnabas'], answer=0,
         explanation='Peter said it to the lame man at the temple gate called Beautiful, and he walked.',
         reference='Acts 3:6'),
    dict(kind='who_said', difficulty='hard', category='acts',
         prompt='Who prayed, "Lord, lay not this sin to their charge," as he was stoned?',
         choices=['Stephen', 'Paul', 'James', 'Philip'], answer=0,
         explanation='Stephen, the first martyr, prayed for those who stoned him.', reference='Acts 7:60'),
    dict(kind='who_said', difficulty='simple', category='law',
         prompt='In the garden, who asked, "Where art thou?"',
         choices=['The LORD God', 'Adam', 'Eve', 'The serpent'], answer=0,
         explanation='The LORD God called to Adam, who had hidden himself.', reference='Genesis 3:9'),
    dict(kind='who_said', difficulty='moderate', category='history',
         prompt='Who asked the people, "How long halt ye between two opinions?"',
         choices=['Elijah', 'Elisha', 'Samuel', 'Nathan'], answer=0,
         explanation='Elijah said it on Mount Carmel, before the fire fell.', reference='1 Kings 18:21'),
    dict(kind='who_said', difficulty='hard', category='history',
         prompt='Who said to King David, "Thou art the man"?',
         choices=['Nathan', 'Gad', 'Samuel', 'Joab'], answer=0,
         explanation='Nathan the prophet told David a parable, then showed him it was about him.',
         reference='2 Samuel 12:7'),
    dict(kind='who_said', difficulty='hard', category='gospels',
         prompt='Who cried, "Lord, I believe; help thou mine unbelief"?',
         choices=['The father of a sick boy', 'Thomas', 'Peter', 'Jairus'], answer=0,
         explanation='A father whose son had a spirit said it, and Jesus healed the boy.', reference='Mark 9:24'),
    dict(kind='who_said', difficulty='simple', category='epistles',
         prompt='Who wrote, "I can do all things through Christ which strengtheneth me"?',
         choices=['Paul', 'Peter', 'James', 'John'], answer=0,
         explanation='Paul wrote it to the Philippians, from prison.', reference='Philippians 4:13'),
    dict(kind='who_said', difficulty='moderate', category='major_prophets',
         prompt='Who said, "Our God whom we serve is able to deliver us from the burning fiery furnace"?',
         choices=['Shadrach, Meshach and Abednego', 'Daniel', 'Nebuchadnezzar', 'Belshazzar'], answer=0,
         explanation='The three Hebrews answered the king, and God delivered them in the fire.',
         reference='Daniel 3:17'),
    dict(kind='who_said', difficulty='moderate', category='history',
         prompt='Who told Samuel, "Man looketh on the outward appearance, but the LORD looketh on the heart"?',
         choices=['The LORD', 'Eli', 'Jesse', 'Saul'], answer=0,
         explanation='The LORD said it when Samuel came to anoint one of Jesse\'s sons.', reference='1 Samuel 16:7'),

    # ── Which came first ──────────────────────────────────────────────────────
    dict(kind='order', difficulty='moderate', category='law', prompt='Which happened first?',
         choices=['The flood', 'The tower of Babel'], answer=0,
         explanation='The flood is in Genesis 7; the tower of Babel in Genesis 11.', reference='Genesis 7:17'),
    dict(kind='order', difficulty='moderate', category='law', prompt='Which happened first?',
         choices=['Joseph was sold into Egypt', 'Moses was born in Egypt'], answer=0,
         explanation='Joseph went down to Egypt (Genesis 37); Moses was born there generations later (Exodus 2).',
         reference='Genesis 37:28'),
    dict(kind='order', difficulty='hard', category='history', prompt='Which king of Judah reigned first?',
         choices=['Hezekiah', 'Josiah'], answer=0,
         explanation='Hezekiah reigned in the days of Isaiah; Josiah, his great-grandson, came later.',
         reference='2 Kings 18:1'),
    dict(kind='order', difficulty='moderate', category='gospels', prompt='Which happened first?',
         choices=['Jesus was baptised', 'Jesus fed the five thousand'], answer=0,
         explanation='His baptism began his ministry (Matthew 3); the feeding came later (Matthew 14).',
         reference='Matthew 3:16'),
    dict(kind='order', difficulty='moderate', category='acts', prompt='Which happened first?',
         choices=['Pentecost', 'Saul\'s conversion'], answer=0,
         explanation='The Spirit came at Pentecost (Acts 2); Saul met Jesus on the Damascus road later (Acts 9).',
         reference='Acts 2:1'),
    dict(kind='order', difficulty='simple', category='history', prompt='Which prophet came first?',
         choices=['Elijah', 'Elisha'], answer=0,
         explanation='Elisha followed Elijah and received a double portion of his spirit.', reference='2 Kings 2:9'),
    dict(kind='order', difficulty='moderate', category='history', prompt='Which happened first?',
         choices=['The walls of Jericho fell', 'Gideon defeated the Midianites'], answer=0,
         explanation='Jericho fell under Joshua (Joshua 6); Gideon judged Israel later (Judges 7).',
         reference='Joshua 6:20'),
    dict(kind='order', difficulty='hard', category='history', prompt='Which happened first?',
         choices=['Judah was carried away to Babylon', 'Nehemiah rebuilt the walls of Jerusalem'], answer=0,
         explanation='Jerusalem fell to Babylon (2 Kings 25); Nehemiah rebuilt its walls after the exile.',
         reference='2 Kings 25:11'),

    # ── Bible facts ───────────────────────────────────────────────────────────
    dict(kind='fact', difficulty='simple', category='gospels', prompt='In which town was Jesus born?',
         choices=['Bethlehem', 'Nazareth', 'Jerusalem', 'Capernaum'], answer=0,
         explanation='Jesus was born in Bethlehem of Judaea, as Micah had foretold.', reference='Matthew 2:1'),
    dict(kind='fact', difficulty='moderate', category='law', prompt='How many sons did Jacob have?',
         choices=['Twelve', 'Ten', 'Seven', 'Thirteen'], answer=0,
         explanation='The sons of Jacob were twelve — the fathers of the tribes of Israel.', reference='Genesis 35:22'),
    dict(kind='fact', difficulty='simple', category='history', prompt='What did David use to defeat Goliath?',
         choices=['A sling and a stone', 'A sword', 'A spear', 'A bow'], answer=0,
         explanation='David slung a stone that sank into the giant\'s forehead.', reference='1 Samuel 17:49'),
    dict(kind='fact', difficulty='moderate', category='history', prompt='Who was the first king of Israel?',
         choices=['Saul', 'David', 'Solomon', 'Samuel'], answer=0,
         explanation='Samuel anointed Saul as the first king.', reference='1 Samuel 10:1'),
    dict(kind='fact', difficulty='moderate', category='history',
         prompt='Which queen came to test Solomon with hard questions?',
         choices=['The queen of Sheba', 'Jezebel', 'Esther', 'Vashti'], answer=0,
         explanation='She heard of Solomon\'s fame and came to prove him with hard questions.', reference='1 Kings 10:1'),
    dict(kind='fact', difficulty='hard', category='history',
         prompt='What did Gideon lay on the floor to ask God for a sign?',
         choices=['A fleece of wool', 'A staff', 'A pot of oil', 'A loaf of bread'], answer=0,
         explanation='Gideon asked for dew on the fleece only, then on the ground only.', reference='Judges 6:37'),
    dict(kind='fact', difficulty='simple', category='gospels', prompt='Who denied Jesus three times?',
         choices=['Peter', 'Judas', 'Thomas', 'John'], answer=0,
         explanation='Peter remembered Jesus\' words when the cock crew, and wept bitterly.', reference='Luke 22:61'),
    dict(kind='fact', difficulty='moderate', category='gospels',
         prompt='Which tax collector climbed a sycamore tree to see Jesus?',
         choices=['Zacchaeus', 'Matthew', 'Nicodemus', 'Bartimaeus'], answer=0,
         explanation='Zacchaeus was little of stature, so he climbed up to see Jesus pass.', reference='Luke 19:4'),
    dict(kind='fact', difficulty='hard', category='gospels', prompt='Who came to Jesus by night?',
         choices=['Nicodemus', 'Joseph of Arimathaea', 'Zacchaeus', 'Lazarus'], answer=0,
         explanation='Nicodemus, a ruler of the Jews, came by night; Jesus told him he must be born again.',
         reference='John 3:2'),
    dict(kind='fact', difficulty='moderate', category='acts', prompt='On which island was Paul shipwrecked?',
         choices=['Melita', 'Cyprus', 'Crete', 'Patmos'], answer=0,
         explanation='All on board came safe to land, on the island called Melita (Malta).', reference='Acts 28:1'),
    dict(kind='fact', difficulty='moderate', category='revelation',
         prompt='On which island was John when he received the Revelation?',
         choices=['Patmos', 'Melita', 'Cyprus', 'Crete'], answer=0,
         explanation='John was on the isle that is called Patmos, for the word of God.', reference='Revelation 1:9'),
    dict(kind='fact', difficulty='simple', category='law',
         prompt='What sign did God give of his promise never again to flood the earth?',
         choices=['A rainbow', 'A dove', 'A star', 'A pillar of cloud'], answer=0,
         explanation='God set his bow in the cloud as a token of the covenant.', reference='Genesis 9:13'),
    dict(kind='fact', difficulty='moderate', category='law',
         prompt='For how many days and nights did it rain in the flood?',
         choices=['Forty', 'Seven', 'Seventy', 'Twelve'], answer=0,
         explanation='The rain was upon the earth forty days and forty nights.', reference='Genesis 7:12'),
    dict(kind='fact', difficulty='moderate', category='law',
         prompt='Which commandment says, "Remember the sabbath day, to keep it holy"?',
         choices=['The fourth', 'The first', 'The third', 'The fifth'], answer=0,
         explanation='The fourth commandment points back to creation: in six days the LORD made heaven and earth.',
         reference='Exodus 20:8'),
    dict(kind='fact', difficulty='hard', category='minor_prophets', prompt='Which prophet married Gomer?',
         choices=['Hosea', 'Amos', 'Micah', 'Joel'], answer=0,
         explanation='Hosea\'s marriage became a picture of God\'s faithful love for unfaithful Israel.',
         reference='Hosea 1:3'),
    dict(kind='fact', difficulty='moderate', category='wisdom', prompt='Who wrote most of the book of Proverbs?',
         choices=['Solomon', 'David', 'Agur', 'Lemuel'], answer=0,
         explanation='The proverbs of Solomon the son of David, king of Israel.', reference='Proverbs 1:1'),
    dict(kind='fact', difficulty='moderate', category='epistles',
         prompt='Which fruit of the Spirit is named first in Galatians 5?',
         choices=['Love', 'Joy', 'Peace', 'Faith'], answer=0,
         explanation='The fruit of the Spirit is love, joy, peace, longsuffering…', reference='Galatians 5:22'),
    dict(kind='fact', difficulty='moderate', category='revelation',
         prompt='In Revelation 14, how many angels carry messages to the whole world?',
         choices=['Three', 'Seven', 'Two', 'Four'], answer=0,
         explanation='Three angels fly in the midst of heaven, each with a message, before the harvest of the earth.',
         reference='Revelation 14:6'),

    # ── True or false ─────────────────────────────────────────────────────────
    dict(kind='true_false', difficulty='simple', category='law',
         prompt='True or false: Eve was made from one of Adam\'s ribs.',
         choices=TRUE_FALSE, answer=0,
         explanation='The LORD God made a woman from the rib he had taken from Adam.', reference='Genesis 2:22'),
    dict(kind='true_false', difficulty='moderate', category='gospels',
         prompt='True or false: Lazarus had been dead four days when Jesus raised him.',
         choices=TRUE_FALSE, answer=0,
         explanation='Martha said, "by this time he stinketh: for he hath been dead four days."', reference='John 11:39'),
    dict(kind='true_false', difficulty='simple', category='history',
         prompt='True or false: Samson\'s strength was in his sandals.',
         choices=TRUE_FALSE, answer=1,
         explanation='It was tied to his Nazarite vow — no razor had come upon his head.', reference='Judges 16:17'),
    dict(kind='true_false', difficulty='hard', category='acts',
         prompt='True or false: Barnabas went with Paul on his second missionary journey.',
         choices=TRUE_FALSE, answer=1,
         explanation='They parted over John Mark: Barnabas sailed to Cyprus, and Paul chose Silas.',
         reference='Acts 15:39'),
    dict(kind='true_false', difficulty='moderate', category='major_prophets',
         prompt='True or false: Daniel prayed three times a day.',
         choices=TRUE_FALSE, answer=0,
         explanation='He kneeled upon his knees three times a day, and prayed, as he did aforetime.',
         reference='Daniel 6:10'),
]

SEED_SW = [
    # ── Mambo ya Biblia ───────────────────────────────────────────────────────
    dict(kind='fact', difficulty='simple', category='law', prompt='Nani alijenga safina?',
         choices=['Nuhu', 'Musa', 'Ibrahimu', 'Yakobo'], answer=0,
         explanation='Mungu alimwagiza Nuhu ajenge safina kabla ya gharika.', reference='Mwanzo 6:14'),
    dict(kind='fact', difficulty='simple', category='law',
         prompt='Mungu alipumzika siku ipi baada ya kazi yake ya uumbaji?',
         choices=['Siku ya saba', 'Siku ya sita', 'Siku ya kwanza', 'Siku ya nane'], answer=0,
         explanation='Siku ya saba Mungu alimaliza kazi yake, akapumzika.', reference='Mwanzo 2:2'),
    dict(kind='fact', difficulty='simple', category='law',
         prompt='Ni ishara gani Mungu aliyoweka kuonyesha hataiangamiza dunia tena kwa gharika?',
         choices=['Upinde wa mvua', 'Njiwa', 'Nyota', 'Nguzo ya wingu'], answer=0,
         explanation='Mungu aliweka upinde wake mawinguni kuwa ishara ya agano.', reference='Mwanzo 9:13'),
    dict(kind='fact', difficulty='moderate', category='law', prompt='Yakobo alikuwa na wana wangapi?',
         choices=['Kumi na wawili', 'Kumi', 'Saba', 'Kumi na watatu'], answer=0,
         explanation='Wana wa Yakobo walikuwa kumi na wawili — baba za makabila ya Israeli.', reference='Mwanzo 35:22'),
    dict(kind='fact', difficulty='moderate', category='law', prompt='Pigo la kwanza juu ya Misri lilikuwa lipi?',
         choices=['Maji kugeuka damu', 'Vyura', 'Chawa', 'Giza'], answer=0,
         explanation='Haruni alipiga maji ya mto, nayo yakageuka damu.', reference='Kutoka 7:20'),
    dict(kind='fact', difficulty='moderate', category='law',
         prompt='Ni amri ipi inayosema, "Ikumbuke siku ya Sabato uitakase"?',
         choices=['Amri ya nne', 'Amri ya kwanza', 'Amri ya tatu', 'Amri ya tano'], answer=0,
         explanation='Amri ya nne inaturudisha kwenye uumbaji: kwa siku sita BWANA alifanya mbingu na nchi.',
         reference='Kutoka 20:8'),
    dict(kind='fact', difficulty='simple', category='history', prompt='Daudi alimshinda Goliathi kwa kutumia nini?',
         choices=['Kombeo na jiwe', 'Upanga', 'Mkuki', 'Upinde'], answer=0,
         explanation='Daudi alitupa jiwe kwa kombeo, likazama katika paji la uso wa Goliathi.',
         reference='1 Samweli 17:49'),
    dict(kind='fact', difficulty='moderate', category='history', prompt='Mfalme wa kwanza wa Israeli alikuwa nani?',
         choices=['Sauli', 'Daudi', 'Sulemani', 'Samweli'], answer=0,
         explanation='Samweli alimtia Sauli mafuta kuwa mfalme wa kwanza.', reference='1 Samweli 10:1'),
    dict(kind='fact', difficulty='moderate', category='history', prompt='Mama yake Samweli aliitwa nani?',
         choices=['Hana', 'Elisabeti', 'Sara', 'Raheli'], answer=0,
         explanation='Hana alimwomba Mungu mtoto, akamwita jina lake Samweli.', reference='1 Samweli 1:20'),
    dict(kind='fact', difficulty='simple', category='history', prompt='Nguvu za Samsoni zilihusiana na nini?',
         choices=['Nywele zake', 'Viatu vyake', 'Upanga wake', 'Mavazi yake'], answer=0,
         explanation='Wembe haukuwahi kupita kichwani pake, kwa kuwa alikuwa Mnadhiri wa Mungu.',
         reference='Waamuzi 16:17'),
    dict(kind='fact', difficulty='moderate', category='history',
         prompt='Ni malkia yupi aliyekuja kumjaribu Sulemani kwa maswali magumu?',
         choices=['Malkia wa Sheba', 'Yezebeli', 'Esta', 'Vashti'], answer=0,
         explanation='Malkia wa Sheba alisikia sifa za Sulemani, akaja kumjaribu kwa maswali magumu.',
         reference='1 Wafalme 10:1'),
    dict(kind='fact', difficulty='simple', category='gospels', prompt='Yesu alizaliwa katika mji gani?',
         choices=['Bethlehemu', 'Nazareti', 'Yerusalemu', 'Kapernaumu'], answer=0,
         explanation='Yesu alizaliwa Bethlehemu ya Uyahudi, kama nabii Mika alivyotabiri.', reference='Mathayo 2:1'),
    dict(kind='fact', difficulty='simple', category='gospels', prompt='Yesu aliwachagua mitume wangapi?',
         choices=['Kumi na wawili', 'Saba', 'Sabini', 'Kumi'], answer=0,
         explanation='Aliwaweka kumi na wawili wawe pamoja naye.', reference='Marko 3:14'),
    dict(kind='fact', difficulty='simple', category='gospels',
         prompt='Katika harusi ya Kana, Yesu aligeuza maji kuwa nini?',
         choices=['Divai', 'Mafuta', 'Maziwa', 'Siki'], answer=0,
         explanation='Hiyo ilikuwa ishara yake ya kwanza.', reference='Yohana 2:9'),
    dict(kind='fact', difficulty='simple', category='gospels', prompt='Nani alimkana Yesu mara tatu?',
         choices=['Petro', 'Yuda', 'Tomaso', 'Yohana'], answer=0,
         explanation='Jogoo alipowika, Petro alikumbuka maneno ya Yesu, akalia kwa uchungu.', reference='Luka 22:61'),
    dict(kind='fact', difficulty='moderate', category='gospels',
         prompt='Mtoza ushuru aliyepanda mkuyu ili amwone Yesu aliitwa nani?',
         choices=['Zakayo', 'Mathayo', 'Nikodemo', 'Bartimayo'], answer=0,
         explanation='Zakayo alikuwa mfupi wa kimo, kwa hiyo alipanda mti amwone Yesu.', reference='Luka 19:4'),
    dict(kind='fact', difficulty='hard', category='gospels', prompt='Nani alikuja kwa Yesu usiku?',
         choices=['Nikodemo', 'Yusufu wa Arimathaya', 'Zakayo', 'Lazaro'], answer=0,
         explanation='Nikodemo, mkuu wa Wayahudi, alikuja usiku; Yesu akamwambia imempasa kuzaliwa mara ya pili.',
         reference='Yohana 3:2'),
    dict(kind='fact', difficulty='moderate', category='gospels',
         prompt='Lazaro alikuwa amekufa siku ngapi Yesu alipomfufua?',
         choices=['Nne', 'Tatu', 'Mbili', 'Saba'], answer=0,
         explanation='Martha alisema alikuwa amekaa kaburini siku nne.', reference='Yohana 11:39'),
    dict(kind='fact', difficulty='moderate', category='major_prophets',
         prompt='Shadraka, Meshaki na Abednego walitupwa wapi?',
         choices=['Katika tanuru la moto', 'Katika tundu la simba', 'Shimoni', 'Baharini'], answer=0,
         explanation='Walikataa kuisujudia sanamu, nao Mungu akawaokoa ndani ya moto.', reference='Danieli 3:21'),
    dict(kind='fact', difficulty='simple', category='major_prophets',
         prompt='Danieli alitupwa wapi kwa sababu ya kumwomba Mungu wake?',
         choices=['Katika tundu la simba', 'Katika tanuru la moto', 'Gerezani', 'Baharini'], answer=0,
         explanation='Mungu alituma malaika wake akafunga vinywa vya simba.', reference='Danieli 6:16'),
    dict(kind='fact', difficulty='simple', category='minor_prophets',
         prompt='Ni nabii yupi aliyemezwa na samaki mkubwa?',
         choices=['Yona', 'Eliya', 'Amosi', 'Hosea'], answer=0,
         explanation='Yona alikaa ndani ya tumbo la samaki siku tatu mchana na usiku.', reference='Yona 1:17'),
    dict(kind='fact', difficulty='moderate', category='acts',
         prompt='Siku ya Pentekoste, ndimi kama za nini zilionekana juu ya wanafunzi?',
         choices=['Moto', 'Maji', 'Nyota', 'Mawingu'], answer=0,
         explanation='Ndimi zilizogawanyika kama za moto zilikaa juu ya kila mmoja wao.', reference='Matendo 2:3'),
    dict(kind='fact', difficulty='simple', category='epistles',
         prompt='Nani aliandika nyaraka nyingi za Agano Jipya?',
         choices=['Paulo', 'Petro', 'Yohana', 'Yakobo'], answer=0,
         explanation='Nyaraka kumi na tatu zinaanza kwa jina la Paulo.', reference='Warumi 1:1'),
    dict(kind='fact', difficulty='moderate', category='revelation',
         prompt='Katika Ufunuo 14, ni malaika wangapi wanaopeleka ujumbe kwa ulimwengu wote?',
         choices=['Watatu', 'Saba', 'Wawili', 'Wanne'], answer=0,
         explanation='Malaika watatu wanaruka katikati ya mbingu, kila mmoja na ujumbe wake.', reference='Ufunuo 14:6'),

    # ── Nani alisema ──────────────────────────────────────────────────────────
    dict(kind='who_said', difficulty='moderate', category='law',
         prompt='Nani alimwambia Farao, "Wape watu wangu ruhusa waende"?',
         choices=['Musa', 'Yoshua', 'Yusufu', 'Eliya'], answer=0,
         explanation='Musa na Haruni walimpelekea Farao neno la BWANA.', reference='Kutoka 5:1'),
    dict(kind='who_said', difficulty='simple', category='history',
         prompt='Nani alisema, "Mimi na nyumba yangu tutamtumikia BWANA"?',
         choices=['Yoshua', 'Musa', 'Kalebu', 'Daudi'], answer=0,
         explanation='Yoshua aliwaambia Israeli wote waliokusanyika Shekemu.', reference='Yoshua 24:15'),
    dict(kind='who_said', difficulty='simple', category='history',
         prompt='Nani alimwambia Naomi, "Watu wako watakuwa watu wangu, na Mungu wako atakuwa Mungu wangu"?',
         choices=['Ruthu', 'Orpa', 'Esta', 'Hana'], answer=0,
         explanation='Ruthu alichagua kubaki na Naomi, na watu wake, na Mungu wake.', reference='Ruthu 1:16'),
    dict(kind='who_said', difficulty='moderate', category='history',
         prompt='Nani alisema, "Nikiangamia, na niangamie"?',
         choices=['Esta', 'Ruthu', 'Debora', 'Hana'], answer=0,
         explanation='Esta aliamua kuingia kwa mfalme ili kuwaombea watu wake.', reference='Esta 4:16'),
    dict(kind='who_said', difficulty='simple', category='gospels',
         prompt='Nani alisema, "Wewe ndiwe Kristo, Mwana wa Mungu aliye hai"?',
         choices=['Petro', 'Yohana', 'Andrea', 'Tomaso'], answer=0,
         explanation='Petro alijibu Yesu alipouliza, "Ninyi mnasema mimi ni nani?"', reference='Mathayo 16:16'),
    dict(kind='who_said', difficulty='moderate', category='gospels',
         prompt='Nani alisema, "Bwana wangu na Mungu wangu"?',
         choices=['Tomaso', 'Petro', 'Mariamu Magdalene', 'Nathanaeli'], answer=0,
         explanation='Tomaso alisema hivyo Yesu aliyefufuka alipomwonyesha mikono na ubavu wake.',
         reference='Yohana 20:28'),
    dict(kind='who_said', difficulty='moderate', category='acts',
         prompt='Nani alisema, "Fedha na dhahabu sina; lakini nilicho nacho ndicho nikupacho"?',
         choices=['Petro', 'Yohana', 'Paulo', 'Barnaba'], answer=0,
         explanation='Petro alimwambia kiwete katika mlango Mzuri wa hekalu, naye akatembea.', reference='Matendo 3:6'),
    dict(kind='who_said', difficulty='moderate', category='gospels',
         prompt='Nani alisema, "Yeye hana budi kuzidi, bali mimi kupungua"?',
         choices=['Yohana Mbatizaji', 'Petro', 'Andrea', 'Nikodemo'], answer=0,
         explanation='Yohana Mbatizaji alisema hivyo kumhusu Yesu.', reference='Yohana 3:30'),

    # ── Kipi kilitangulia ─────────────────────────────────────────────────────
    dict(kind='order', difficulty='moderate', category='law', prompt='Kipi kilitangulia?',
         choices=['Gharika', 'Mnara wa Babeli'], answer=0,
         explanation='Gharika iko Mwanzo 7; mnara wa Babeli uko Mwanzo 11.', reference='Mwanzo 7:17'),
    dict(kind='order', difficulty='moderate', category='law', prompt='Kipi kilitangulia?',
         choices=['Yusufu kuuzwa Misri', 'Kuzaliwa kwa Musa'], answer=0,
         explanation='Yusufu alipelekwa Misri (Mwanzo 37); Musa alizaliwa huko vizazi vingi baadaye (Kutoka 2).',
         reference='Mwanzo 37:28'),
    dict(kind='order', difficulty='moderate', category='gospels', prompt='Kipi kilitangulia?',
         choices=['Yesu kubatizwa', 'Yesu kulisha watu elfu tano'], answer=0,
         explanation='Ubatizo wake ulianza huduma yake (Mathayo 3); kulisha watu kulifuata (Mathayo 14).',
         reference='Mathayo 3:16'),
    dict(kind='order', difficulty='moderate', category='acts', prompt='Kipi kilitangulia?',
         choices=['Pentekoste', 'Kuongoka kwa Sauli'], answer=0,
         explanation='Roho alikuja Pentekoste (Matendo 2); Sauli alikutana na Yesu njiani kwenda Dameski baadaye (Matendo 9).',
         reference='Matendo 2:1'),
    dict(kind='order', difficulty='simple', category='history', prompt='Ni nabii yupi aliyetangulia?',
         choices=['Eliya', 'Elisha'], answer=0,
         explanation='Elisha alimfuata Eliya, akapokea sehemu mbili za roho yake.', reference='2 Wafalme 2:9'),

    # ── Kweli au si kweli ─────────────────────────────────────────────────────
    dict(kind='true_false', difficulty='simple', category='law',
         prompt='Kweli au si kweli: Hawa aliumbwa kutokana na ubavu wa Adamu.',
         choices=KWELI, answer=0,
         explanation='BWANA Mungu alimfanya mwanamke kwa ule ubavu aliotwaa kwa Adamu.', reference='Mwanzo 2:22'),
    dict(kind='true_false', difficulty='moderate', category='gospels',
         prompt='Kweli au si kweli: Yesu alizaliwa Nazareti.',
         choices=KWELI, answer=1,
         explanation='Alizaliwa Bethlehemu, akakulia Nazareti.', reference='Mathayo 2:1'),
    dict(kind='true_false', difficulty='moderate', category='major_prophets',
         prompt='Kweli au si kweli: Danieli aliomba mara tatu kwa siku.',
         choices=KWELI, answer=0,
         explanation='Alipiga magoti mara tatu kila siku, akaomba, kama alivyofanya tangu zamani.',
         reference='Danieli 6:10'),
    dict(kind='true_false', difficulty='moderate', category='acts',
         prompt='Kweli au si kweli: Sauli alikutana na Yesu aliyefufuka njiani kwenda Dameski.',
         choices=KWELI, answer=0,
         explanation='Nuru kutoka mbinguni ilimwangaza, akasikia sauti ya Yesu.', reference='Matendo 9:3'),
    dict(kind='true_false', difficulty='hard', category='history',
         prompt='Kweli au si kweli: Musa aliwaongoza Waisraeli kuvuka Yordani kuingia Kanaani.',
         choices=KWELI, answer=1,
         explanation='Yoshua ndiye aliyewavusha Yordani; Musa aliiona nchi kutoka mlima Nebo.', reference='Yoshua 3:17'),
]

# The story journey, in the order it is played. Book numbers are canonical
# (Genesis 1 … Revelation 66).
STORY_PACKS = [
    ('creation', 'Creation and the Fall', 'Uumbaji na Anguko', 1, 1, 3,
     'Six days, a seventh of rest, a garden and a choice.', 'Siku sita, siku ya saba ya pumziko, bustani na uchaguzi.', 'leaf-outline'),
    ('noah', 'Noah and the Flood', 'Nuhu na Gharika', 1, 6, 9,
     'An ark, forty days of rain and a rainbow.', 'Safina, siku arobaini za mvua na upinde wa mvua.', 'boat-outline'),
    ('abraham', 'Abraham\'s Journey', 'Safari ya Ibrahimu', 1, 12, 22,
     'Called out of Ur to a land he did not know.', 'Aliitwa kutoka Uru kwenda nchi asiyoijua.', 'walk-outline'),
    ('joseph', 'Joseph', 'Yusufu', 1, 37, 50,
     'A coat, a pit, a prison and a palace.', 'Kanzu, shimo, gereza na jumba la kifalme.', 'shirt-outline'),
    ('exodus', 'Moses and the Exodus', 'Musa na Kutoka', 2, 1, 15,
     'From the bulrushes to the Red Sea.', 'Kutoka kwenye manyasi hadi Bahari ya Shamu.', 'water-outline'),
    ('sinai', 'The Law at Sinai', 'Sheria Sinai', 2, 19, 24,
     'Thunder on the mountain and ten words in stone.', 'Radi mlimani na amri kumi juu ya mawe.', 'reader-outline'),
    ('gideon', 'Gideon', 'Gideoni', 7, 6, 8,
     'Three hundred men, trumpets and torches.', 'Watu mia tatu, tarumbeta na mienge.', 'flame-outline'),
    ('ruth', 'Ruth', 'Ruthu', 8, 1, 4,
     'Loyal love, a field of barley and a redeemer.', 'Upendo mwaminifu, shamba la shayiri na mkombozi.', 'heart-outline'),
    ('david', 'Young David', 'Daudi Kijana', 9, 16, 20,
     'A shepherd boy, a giant and a friend.', 'Kijana mchungaji, jitu na rafiki.', 'shield-outline'),
    ('elijah', 'Elijah', 'Eliya', 11, 17, 19,
     'Ravens, fire on Carmel and a still small voice.', 'Kunguru, moto Karmeli na sauti ndogo ya utulivu.', 'bonfire-outline'),
    ('esther', 'Esther', 'Esta', 17, 1, 10,
     'A queen for such a time as this.', 'Malkia kwa wakati kama huu.', 'diamond-outline'),
    ('daniel', 'Daniel', 'Danieli', 27, 1, 6,
     'Faithful in Babylon — the furnace and the lions.', 'Mwaminifu Babeli — tanuru na simba.', 'paw-outline'),
    ('jonah', 'Jonah', 'Yona', 32, 1, 4,
     'A runaway prophet and a God of second chances.', 'Nabii aliyekimbia na Mungu wa nafasi ya pili.', 'fish-outline'),
    ('birth', 'The Birth of Jesus', 'Kuzaliwa kwa Yesu', 42, 1, 2,
     'Angels, shepherds and a manger in Bethlehem.', 'Malaika, wachungaji na hori Bethlehemu.', 'star-outline'),
    ('sermon', 'The Sermon on the Mount', 'Mahubiri ya Mlimani', 40, 5, 7,
     'The Beatitudes, the Lord\'s Prayer and the house on the rock.', 'Heri, Sala ya Bwana na nyumba juu ya mwamba.', 'sunny-outline'),
    ('passion', 'The Passion Week', 'Wiki ya Mateso', 40, 26, 28,
     'The upper room, the cross and the empty tomb.', 'Chumba cha juu, msalaba na kaburi tupu.', 'add-outline'),
    ('pentecost', 'Pentecost and the Early Church', 'Pentekoste na Kanisa la Kwanza', 44, 1, 4,
     'Wind, fire and three thousand in a day.', 'Upepo, moto na watu elfu tatu kwa siku moja.', 'people-outline'),
    ('paul', 'Paul\'s Calling and First Journey', 'Wito na Safari ya Kwanza ya Paulo', 44, 9, 14,
     'Light on the Damascus road and the gospel to the nations.', 'Nuru njiani kwenda Dameski na injili kwa mataifa.', 'compass-outline'),
]
