# Generated by Django 5.1.4 on 2025-01-16 00:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_remove_track_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
