# Generated by Django 5.1.4 on 2025-01-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='picture',
        ),
    ]
