# Generated by Django 5.1.4 on 2025-01-20 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_rename_avatar_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
