# Generated by Django 5.2 on 2026-06-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0021_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='song_end_time',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='song_start_time',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read'], name='songs_notif_recipie_8fa5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='songs_notif_recipie_e363d5_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['-created_at'], name='songs_socia_created_e7525a_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['expires_at'], name='songs_story_expires_5b8366_idx'),
        ),
    ]
