# Generated by Django 5.2 on 2026-06-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0023_trigram_search_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='is_favorite',
        ),
    ]
