# Generated by Django 5.2 on 2026-06-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0024_remove_track_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='song_artist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='song_audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='song_end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='song_start_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='song_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
