# Generated by Django 5.2 on 2026-06-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0026_heal_corrupted_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
