# Generated by Django 5.2 on 2026-06-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0027_socialpost_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='video_end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='video_start_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
