# Generated by Django 5.2 on 2026-06-11 11:54

from django.db import migrations

DEFAULTS = [
    {'name': 'Hope Channel TV', 'type': 'TV', 'website': 'https://www.hopetv.org', 'youtube': 'https://www.youtube.com/@HopeChannel'},
    {'name': '3ABN', 'type': 'TV', 'website': 'https://www.3abn.org', 'youtube': 'https://www.youtube.com/@3abnnetwork'},
    {'name': 'LLBN', 'type': 'TV', 'website': 'https://www.llbn.tv'},
    {'name': 'Adventist World Radio', 'type': 'Radio', 'website': 'https://www.awr.org'},
    {'name': 'Voice of Prophecy', 'type': 'Radio', 'website': 'https://www.voiceofprophecy.com'},
    {'name': 'Faith FM', 'type': 'Radio', 'website': 'https://www.faithfm.com.au'},
    {'name': 'Adventist Review Podcast', 'type': 'Podcast', 'website': 'https://www.adventistreview.org/podcasts'},
    {'name': 'Amazing Facts', 'type': 'Podcast', 'website': 'https://www.amazingfacts.org/media-library/podcasts'},
]


def seed(apps, schema_editor):
    MediaStation = apps.get_model('songs', 'MediaStation')
    for d in DEFAULTS:
        # created_by left null -> system-owned, read-only for all users.
        MediaStation.objects.get_or_create(name=d['name'], defaults=d)


def unseed(apps, schema_editor):
    MediaStation = apps.get_model('songs', 'MediaStation')
    MediaStation.objects.filter(
        name__in=[d['name'] for d in DEFAULTS], created_by__isnull=True
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0029_mediastation'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
