# Generated by Django 5.2 on 2026-06-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0032_publicationbookmark_publicationlike_readingprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choir',
            name='cover_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='choir',
            name='profile_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
