# Generated by Django 5.2 on 2026-06-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0033_alter_choir_cover_image_alter_choir_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostudio',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='videostudio',
            name='rate_description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='videostudio',
            name='cover_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='videostudio',
            name='logo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
