# Generated by Django 5.2 on 2026-06-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0035_message_attachment_message_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppost',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='groupmember',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='attachment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Voice note'), ('system', 'System')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='songs.grouppost'),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
