# Generated by Django 6.0.5 on 2026-06-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0037_remove_church_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bank_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mpesa_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='payment_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='till_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
