# Generated by Django 6.0.5 on 2026-06-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0041_alter_postcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
