# Generated by Django 6.0.5 on 2026-06-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0044_search_trgm_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['track', '-created_at'], name='trackcomment_track_created_idx'),
        ),
    ]
