# Generated by Django 5.2 on 2026-06-17 22:44

from django.db import migrations


def seed_roles(apps, schema_editor):
    Role = apps.get_model('songs', 'Role')
    defaults = {
        'Content Moderator': ['handle_reports', 'remove_content', 'manage_appeals'],
        'Community Manager': ['handle_reports', 'remove_content', 'manage_users', 'manage_appeals'],
        'Analyst': ['view_analytics', 'view_audit_log'],
    }
    for name, caps in defaults.items():
        Role.objects.get_or_create(name=name, defaults={'capabilities': caps})


def unseed_roles(apps, schema_editor):
    Role = apps.get_model('songs', 'Role')
    Role.objects.filter(name__in=['Content Moderator', 'Community Manager', 'Analyst']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0050_role_user_role'),
    ]

    operations = [
        migrations.RunPython(seed_roles, unseed_roles),
    ]
