# Generated by Django 5.2 on 2026-06-18 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0051_seed_default_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('radio', 'Radio'), ('tv', 'TV'), ('podcast', 'Podcast')], default='radio', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('ended', 'Ended')], default='live', max_length=10)),
                ('viewer_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CoHostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('left', 'Left')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohost_requests', to=settings.AUTH_USER_MODEL)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohost_requests', to='songs.livebroadcast')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='livebroadcast',
            index=models.Index(fields=['status', '-started_at'], name='songs_liveb_status_040ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='cohostrequest',
            index=models.Index(fields=['broadcast', 'status'], name='songs_cohos_broadca_a1e958_idx'),
        ),
    ]
