# Generated by Django 6.0.5 on 2026-06-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0052_livebroadcast_cohostrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livebroadcast',
            name='peak_viewer_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
