# Generated by Django 5.2 on 2026-06-19 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0053_livebroadcast_peak_viewer_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoirJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='songs.choir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choir_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('choir', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChoirMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('friend', 'Friend')], default='friend', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('choir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='songs.choir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choir_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['choir', 'role'], name='songs_choir_choir_i_1adf75_idx')],
                'unique_together': {('choir', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChoirMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Voice note'), ('system', 'System')], default='text', max_length=10)),
                ('attachment', models.TextField(blank=True, default='')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='songs.choir')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='songs.choirmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choir_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['choir', 'created_at'], name='songs_choir_choir_i_d08383_idx')],
            },
        ),
    ]
