# Generated by Django 5.2 on 2026-06-21 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0057_grouppostreaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Voice note'), ('system', 'System')], default='text', max_length=10)),
                ('attachment', models.TextField(blank=True, default='')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='songs.church')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='songs.churchmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChurchMessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='songs.churchmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='songs.church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('church', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChurchMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('friend', 'Friend')], default='friend', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='songs.church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['church', 'role'], name='songs_churc_church__31906b_idx')],
                'unique_together': {('church', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='churchmessage',
            index=models.Index(fields=['church', 'created_at'], name='songs_churc_church__50c229_idx'),
        ),
        migrations.AddIndex(
            model_name='churchmessagereaction',
            index=models.Index(fields=['message'], name='songs_churc_message_d16358_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='churchmessagereaction',
            unique_together={('message', 'user')},
        ),
    ]
