# Generated by Django 5.2 on 2026-06-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0058_churchmessage_churchmessagereaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='theme',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
