# Generated by Django 6.0.5 on 2026-06-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0061_group_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='choir',
            name='only_admins_can_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='church',
            name='only_admins_can_post',
            field=models.BooleanField(default=False),
        ),
    ]
