# Generated by Django 6.0.5 on 2026-06-24 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0063_adminnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=True)),
                ('comments', models.BooleanField(default=True)),
                ('follows', models.BooleanField(default=True)),
                ('messages', models.BooleanField(default=True)),
                ('groups', models.BooleanField(default=True)),
                ('communities', models.BooleanField(default=True)),
                ('live', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
