# Generated by Django 6.0.5 on 2026-06-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0065_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
