# Generated by Django 6.0.5 on 2026-06-25 11:29

from django.db import migrations, models


def forwards(apps, schema_editor):
    LiveBroadcast = apps.get_model('songs', 'LiveBroadcast')
    # 'radio' is renamed to 'meet'; 'podcast' folded into 'tv' (both are video).
    LiveBroadcast.objects.filter(kind='radio').update(kind='meet')
    LiveBroadcast.objects.filter(kind='podcast').update(kind='tv')


def backwards(apps, schema_editor):
    LiveBroadcast = apps.get_model('songs', 'LiveBroadcast')
    LiveBroadcast.objects.filter(kind='meet').update(kind='radio')


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0066_user_deactivated_at_user_is_deactivated'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='livebroadcast',
            name='kind',
            field=models.CharField(choices=[('meet', 'Meet'), ('tv', 'Go-Live')], default='meet', max_length=10),
        ),
    ]
