# Generated by Django 6.0.5 on 2026-06-25 13:52

from django.db import migrations


def dedupe(apps, schema_editor):
    """Collapse any pre-existing duplicate (broadcast, user) rows — keeping the
    newest — so the unique constraint can be applied cleanly."""
    CoHostRequest = apps.get_model('songs', 'CoHostRequest')
    seen = set()
    for row in CoHostRequest.objects.order_by('-id').values('id', 'broadcast_id', 'user_id'):
        key = (row['broadcast_id'], row['user_id'])
        if key in seen:
            CoHostRequest.objects.filter(id=row['id']).delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0067_live_kind_meet_tv'),
    ]

    operations = [
        migrations.RunPython(dedupe, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='cohostrequest',
            unique_together={('broadcast', 'user')},
        ),
    ]
