# Generated by Django 5.2 on 2026-07-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0068_cohostrequest_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='cover_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='grouppostattachment',
            name='file',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='media_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
