# Generated by Django 5.2 on 2026-07-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0070_blank_cloudinary_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
