# Generated by Django 5.2 on 2026-07-17 12:52
#
# Move Choir/Videostudio/MediaStation/Publication cover & logo images off the
# old base64-data-URI storage onto R2 URLs. The columns shrink from TextField to
# varchar(500), so the existing base64 blobs (dev test data) MUST be blanked
# first or the ALTER would overflow the new length. Images are re-added by
# re-uploading; inline article-body images stay base64 for now.

from django.db import migrations, models


def blank_base64_media(apps, schema_editor):
    targets = [
        ('Choir', ('profile_image', 'cover_image')),
        ('Videostudio', ('logo', 'cover_image')),
        ('MediaStation', ('logo',)),
        ('Publication', ('cover',)),
    ]
    for model_name, fields in targets:
        model = apps.get_model('songs', model_name)
        for field in fields:
            # Only clear leftover base64 / non-URL values; keep any real URLs.
            for row in model.objects.exclude(**{field: ''}).iterator():
                val = getattr(row, field) or ''
                if not val.startswith(('http://', 'https://')):
                    setattr(row, field, '')
                    row.save(update_fields=[field])


class Migration(migrations.Migration):

    # Non-atomic so the blanking DML commits before the column-type ALTERs —
    # Postgres refuses to ALTER a table with pending trigger events in the same
    # transaction as row updates.
    atomic = False

    dependencies = [
        ('songs', '0071_socialpost_thumbnail'),
    ]

    operations = [
        # Blank base64 blobs while the columns are still TextField.
        migrations.RunPython(blank_base64_media, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='choir',
            name='cover_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='choir',
            name='profile_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='mediastation',
            name='logo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='videostudio',
            name='cover_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='videostudio',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
