# Generated by Django 5.2 on 2026-07-23 10:43

from django.db import migrations, models


def mark_paid_orders_committed(apps, schema_editor):
    """Orders already PAID (via the Stripe path) had their inventory decremented
    at fulfilment time. Without this backfill they would look uncommitted, and a
    seller confirming one under the new direct-pay flow would decrement a second
    time. Their payment is already settled, so stamp both flags."""
    OrderItem = apps.get_model('songs', 'OrderItem')
    OrderItem.objects.filter(order__payment_status='PAID').update(stock_committed=True)
    for item in OrderItem.objects.filter(
        order__payment_status='PAID', payment_confirmed_at__isnull=True
    ).select_related('order').iterator():
        item.payment_confirmed_at = item.order.updated_at
        item.save(update_fields=['payment_confirmed_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0074_watch_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock_committed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_paid_orders_committed, migrations.RunPython.noop),
    ]
