# Generated by Django 5.2 on 2026-07-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0079_seed_legacy_wallpapers'),
    ]

    operations = [
        migrations.AddField(
            model_name='choir',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='choirmessage',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='church',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='churchmessage',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='mediastation',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='videostudio',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
