# Generated by Django 5.2 on 2026-07-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0080_choir_is_removed_choirmessage_is_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostudio',
            name='category',
            field=models.CharField(choices=[('media', 'Media & Production'), ('hospitality', 'Hospitality'), ('health', 'Health & Wellness'), ('professional', 'Professional'), ('home', 'Home & Trades')], db_index=True, default='media', max_length=20),
        ),
    ]
