# Generated by Django 5.2 on 2026-07-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0081_videostudio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostudio',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videostudio',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videostudio',
            name='tiktok_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videostudio',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videostudio',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
