# Generated by Django 5.2 on 2026-07-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0083_notification_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='attachment_blurhash',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
