# Generated by Django 5.2 on 2026-07-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0084_grouppost_attachment_blurhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
