# Generated by Django 5.2 on 2026-07-24 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0085_grouppost_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pinned_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='songs.grouppost'),
        ),
    ]
