# Generated by Django 5.2 on 2026-07-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0086_group_pinned_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='join_question',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
