# Generated by Django 5.2 on 2026-07-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0087_group_join_question_groupjoinrequest_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
