# Generated by Django 5.2 on 2026-07-24 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0088_groupmember_is_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='songs.group')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', '-created_at'], name='songs_group_group_i_9b6acc_idx')],
            },
        ),
    ]
