# Generated by Django 5.2 on 2026-07-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0089_groupauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='choirmessage',
            name='attachment_blurhash',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='churchmessage',
            name='attachment_blurhash',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
