# Generated by Django 5.2 on 2026-07-25 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0090_choirmessage_attachment_blurhash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choir',
            name='pinned_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='songs.choirmessage'),
        ),
        migrations.AddField(
            model_name='choirmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='pinned_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='songs.churchmessage'),
        ),
        migrations.AddField(
            model_name='churchmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
