# Generated by Django 5.2 on 2026-07-25 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0091_choir_pinned_message_choirmessage_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choirmembership',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='churchmembership',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CommunityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('choir', 'Choir'), ('church', 'Church')], db_index=True, max_length=10)),
                ('community_id', models.PositiveIntegerField(db_index=True)),
                ('action', models.CharField(max_length=40)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'community_id', '-created_at'], name='songs_commu_kind_0f9b12_idx')],
            },
        ),
    ]
