# Generated by Django 5.2 on 2026-07-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0092_choirmembership_is_moderator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livebroadcast',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
