# Generated by Django 5.2 on 2026-07-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0093_livebroadcast_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='livebroadcast',
            name='overlay',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
