# Generated by Django 5.2 on 2026-09-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0098_remove_choirjoinrequest_choir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='kind',
            field=models.CharField(choices=[('group', 'Group'), ('community', 'Community')], db_index=True, default='group', max_length=12),
        ),
    ]
