# Generated by Django 5.2 on 2026-09-03 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0100_split_groups_from_communities'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Daily quizzes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(db_index=True, max_length=40)),
                ('book_number', models.PositiveSmallIntegerField(db_index=True)),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['book_number', 'chapter', 'verse'],
                'indexes': [models.Index(fields=['book_number', 'chapter'], name='songs_bible_book_nu_7c3d97_idx')],
                'unique_together': {('book', 'chapter', 'verse')},
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('answers', models.JSONField(default=dict)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='songs.dailyquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'duration_seconds'],
                'indexes': [models.Index(fields=['quiz', '-score'], name='songs_quiza_quiz_id_a7f088_idx')],
                'unique_together': {('user', 'quiz')},
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('difficulty', models.CharField(choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('hard', 'Hard')], db_index=True, max_length=10)),
                ('kind', models.CharField(choices=[('book', 'Which book'), ('blank', 'Missing word'), ('reference', 'Which reference'), ('order', 'Which comes first')], max_length=12)),
                ('prompt', models.TextField()),
                ('passage', models.TextField(blank=True, default='')),
                ('choices', models.JSONField(default=list)),
                ('answer_index', models.PositiveSmallIntegerField()),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='songs.dailyquiz')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('quiz', 'order')},
            },
        ),
    ]
