# Generated by Django 5.2 on 2026-09-03 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0101_dailyquiz_bibleverse_quizattempt_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.PositiveSmallIntegerField(default=0)),
                ('response_seconds', models.FloatField(blank=True, null=True)),
                ('streak_after', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['question__order'],
            },
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-points', '-score', 'duration_seconds']},
        ),
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='songs_quiza_quiz_id_a7f088_idx',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='longest_streak',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='points',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='base_points',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='category',
            field=models.CharField(blank=True, choices=[('law', 'The Law'), ('history', 'History'), ('wisdom', 'Wisdom'), ('major_prophets', 'Major Prophets'), ('minor_prophets', 'Minor Prophets'), ('gospels', 'Gospels'), ('acts', 'Acts'), ('epistles', 'Epistles'), ('revelation', 'Revelation')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', '-points'], name='songs_quiza_quiz_id_63bc26_idx'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_rows', to='songs.quizattempt'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='songs.quizquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
