# Generated by Django 5.2 on 2026-09-03 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0102_quizanswer_alter_quizattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='songs.dailyquiz'),
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(db_index=True, max_length=12)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('answered', models.PositiveSmallIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('streak', models.PositiveSmallIntegerField(default=0)),
                ('longest_streak', models.PositiveSmallIntegerField(default=0)),
                ('is_finished', models.BooleanField(db_index=True, default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'order')},
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='songs.quizsession'),
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'order'), ('session', 'order')},
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quiz__isnull', False), ('session__isnull', True)), models.Q(('quiz__isnull', True), ('session__isnull', False)), _connector='OR'), name='question_belongs_to_one_owner'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['user', 'mode', '-points'], name='songs_quizs_user_id_8cd3e1_idx'),
        ),
    ]
