# Generated by Django 5.2 on 2026-09-03 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0103_alter_quizquestion_quiz_quizsession_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_rows', to='songs.quizsession'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_rows', to='songs.quizattempt'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('attempt', 'question'), ('session', 'question')},
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attempt__isnull', False), ('session__isnull', True)), models.Q(('attempt__isnull', True), ('session__isnull', False)), _connector='OR'), name='answer_belongs_to_one_owner'),
        ),
    ]
