# Generated by Django 5.2 on 2026-09-03 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0104_alter_quizanswer_unique_together_quizanswer_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='quiz',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='QuizReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
