# Generated by Django 5.2 on 2026-09-03 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0105_notificationpreference_quiz_quizreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('icon', models.CharField(blank=True, default='book', max_length=40)),
                ('source', models.JSONField(default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WordPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('size', models.PositiveSmallIntegerField()),
                ('grid', models.JSONField(default=list)),
                ('placements', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='songs.puzzletheme')),
            ],
            options={
                'ordering': ['theme__order', 'level'],
                'unique_together': {('theme', 'level')},
            },
        ),
        migrations.CreateModel(
            name='PuzzleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found', models.JSONField(default=list)),
                ('hints_used', models.PositiveSmallIntegerField(default=0)),
                ('coins_earned', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(db_index=True, default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_progress', to=settings.AUTH_USER_MODEL)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='songs.wordpuzzle')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('user', 'puzzle')},
            },
        ),
        migrations.CreateModel(
            name='CoinSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('hint', 'Puzzle hint')], default='hint', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_spends', to=settings.AUTH_USER_MODEL)),
                ('puzzle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='songs.wordpuzzle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='songs_coins_user_id_c4c206_idx')],
            },
        ),
    ]
