# Generated by Django 5.2 on 2026-09-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0107_seed_puzzle_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzleprogress',
            name='hinted',
            field=models.JSONField(default=list),
        ),
    ]
