# Generated by Django 5.2 on 2026-09-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0108_puzzleprogress_hinted'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=24, unique=True)),
                ('length', models.PositiveSmallIntegerField(db_index=True)),
                ('letters', models.CharField(db_index=True, max_length=24)),
                ('frequency', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['-frequency', 'word'],
                'indexes': [models.Index(fields=['length', '-frequency'], name='songs_bible_length_33e0df_idx')],
            },
        ),
    ]
