# Generated by Django 5.2 on 2026-09-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0109_bibleword'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpuzzle',
            name='letters',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
