# Generated by Django 5.2 on 2026-09-03 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0110_wordpuzzle_letters'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzleprogress',
            name='bonus',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='wordpuzzle',
            name='bonus_words',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='wordpuzzle',
            name='verse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puzzles', to='songs.bibleverse'),
        ),
        migrations.CreateModel(
            name='PlayDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='songs_playd_user_id_e05488_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
