# Generated by Django 5.2 on 2026-09-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0113_notificationpreference_weather_weatherplace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherplace',
            name='region',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
