# Generated by Django 5.2 on 2026-09-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0115_notificationpreference_verse_versesend'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['user', '-created_at'], name='socialpost_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['-created_at'], name='track_created_idx'),
        ),
    ]
