# Generated by Django 5.2 on 2026-09-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0116_socialpost_socialpost_user_created_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='message_conv_created_idx'),
        ),
    ]
