# Generated by Django 5.2 on 2026-09-21 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0117_message_conv_created_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='socialpost',
            name='client_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='comments_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='visibility',
            field=models.CharField(choices=[('public', 'Everyone'), ('followers', 'Followers'), ('private', 'Only me')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='track',
            name='client_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('artist', 'client_id'), name='track_artist_client_id_uniq'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='songs.hashtag'),
        ),
        migrations.AddConstraint(
            model_name='socialpost',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('user', 'client_id'), name='socialpost_user_client_id_uniq'),
        ),
    ]
