# Generated by Django 5.2 on 2026-09-23 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0121_track_comment_threads'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_id', models.CharField(max_length=64)),
                ('ms_played', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('counted', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, default='', max_length=24)),
                ('network', models.CharField(blank=True, default='', max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_events', to='songs.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-started_at'], name='playevent_user_recent_idx'), models.Index(fields=['track', '-started_at'], name='playevent_track_recent_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'play_id'), name='playevent_user_play_uniq')],
            },
        ),
    ]
