# Generated by Django 5.2 on 2026-09-23 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0122_track_duration_play_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_high',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='track',
            name='audio_low',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='track',
            name='audio_standard',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='track',
            name='cover_medium',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='track',
            name='cover_small',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='track',
            name='loudness_lufs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='processed_source',
            field=models.CharField(blank=True, default='', max_length=1100),
        ),
        migrations.AddField(
            model_name='track',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='track',
            name='waveform',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('key', models.CharField(blank=True, default='', max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('run_after', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'run_after'], name='job_ready_idx'), models.Index(fields=['kind', 'key', 'status'], name='job_dedupe_idx')],
            },
        ),
    ]
