# Generated by Django 5.2 on 2026-09-23 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0125_playlist_order_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='playevent',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.CreateModel(
            name='ChartEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.CharField(max_length=12)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('position', models.PositiveSmallIntegerField()),
                ('plays', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_entries', to='songs.track')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['chart', 'country', 'position'], name='chart_lookup_idx')],
            },
        ),
    ]
