# Generated by Django 5.2 on 2026-09-23 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0127_seed_genres_first_charts'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_artist',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('cover_image', models.CharField(blank=True, default='', max_length=500)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='track',
            name='album_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='songs.album'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist', '-created_at'], name='album_artist_idx'),
        ),
    ]
