# Generated by Django 5.2 on 2026-09-23 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0129_albums_from_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='kind',
            field=models.CharField(choices=[('suspension', 'Suspension'), ('copyright', 'Song takedown')], default='suspension', max_length=20),
        ),
        migrations.AddField(
            model_name='appeal',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='songs.track'),
        ),
        migrations.AddField(
            model_name='track',
            name='composer',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='track',
            name='isrc',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='track',
            name='license',
            field=models.CharField(choices=[('all_rights_reserved', 'All rights reserved'), ('public_domain', 'Public domain'), ('creative_commons', 'Creative Commons')], default='all_rights_reserved', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='producer',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='track',
            name='removal_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='track',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='removed_reason',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='rights_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='rights_holder',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
