# Generated by Django 5.2 on 2026-09-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0130_track_rights_disputes'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='spectrum',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
