# Generated by Django 5.2 on 2026-09-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0139_organizations_and_book_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostudio',
            name='featured_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='videostudio',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='videostudio',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
