# Generated by Django 5.2 on 2026-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0143_messages_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='client_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='grouppost',
            index=models.Index(fields=['group', 'created_at', 'id'], name='grouppost_group_time'),
        ),
        migrations.AddConstraint(
            model_name='grouppost',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('user', 'client_id'), name='uniq_grouppost_client_id'),
        ),
    ]
