# Generated by Django 5.2 on 2026-09-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0144_groups_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='invite_max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='invite_uses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='slow_mode_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
