# Generated by Django 5.2 on 2026-09-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0145_groups_safety'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='notify_level',
            field=models.CharField(choices=[('all', 'All messages'), ('mentions', 'Mentions only')], default='all', max_length=10),
        ),
    ]
