# Generated by Django 5.2 on 2026-09-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0146_groups_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='notices',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notices_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
