# Generated by Django 5.2 on 2026-09-26 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def old_notices_were_announced(apps, schema_editor):
    # Everything already on the board was seen in its day: never push it now.
    apps.get_model('songs', 'Notice').objects.update(announced=True)


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0147_notices_reach'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnote',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminnote',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminnote',
            name='reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notice',
            name='announced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='publish_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(old_notices_were_announced, migrations.RunPython.noop),
    ]
