# Generated by Django 5.2 on 2026-09-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0148_notices_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('event', 'Event'), ('urgent', 'Urgent'), ('prayer', 'Prayer')], db_index=True, default='general', max_length=12),
        ),
        migrations.AddField(
            model_name='notice',
            name='cover_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
