# Generated by Django 5.2 on 2026-09-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0149_notices_rich'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='cover_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='cover_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
