# Generated by Django 5.2 on 2026-09-29 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0150_notices_cover_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerseDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='songs_verse_user_id_fe8634_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
