# Generated by Django 5.2 on 2026-09-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0151_verse_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='playday',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coinspend',
            name='reason',
            field=models.CharField(choices=[('hint', 'Puzzle hint'), ('freeze', 'Streak freeze')], default='hint', max_length=20),
        ),
    ]
