# Generated by Django 5.2 on 2026-09-29 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0152_streak_freeze'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('who_said', 'Who said this'), ('true_false', 'True or false'), ('order', 'Which came first'), ('fact', 'Bible fact')], max_length=12)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili')], db_index=True, default='en', max_length=5)),
                ('difficulty', models.CharField(choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('hard', 'Hard')], db_index=True, max_length=10)),
                ('category', models.CharField(blank=True, choices=[('law', 'The Law'), ('history', 'History'), ('wisdom', 'Wisdom'), ('major_prophets', 'Major Prophets'), ('minor_prophets', 'Minor Prophets'), ('gospels', 'Gospels'), ('acts', 'Acts'), ('epistles', 'Epistles'), ('revelation', 'Revelation')], default='', max_length=20)),
                ('prompt', models.TextField()),
                ('choices', models.JSONField(default=list)),
                ('answer_index', models.PositiveSmallIntegerField()),
                ('explanation', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('retired_reason', models.CharField(blank=True, choices=[('too_easy', 'Almost everyone got it right'), ('too_hard', 'Almost everyone got it wrong — check the answer')], default='', max_length=12)),
                ('times_asked', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['language', 'difficulty', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='kind',
            field=models.CharField(choices=[('book', 'Which book'), ('blank', 'Missing word'), ('reference', 'Which reference'), ('order', 'Which comes first'), ('who_said', 'Who said this'), ('true_false', 'True or false'), ('fact', 'Bible fact')], max_length=12),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='bank_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uses', to='songs.bankquestion'),
        ),
    ]
