# Generated by Django 5.2 on 2026-09-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0154_question_bank_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquiz',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='dailyquiz',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailyquiz',
            unique_together={('date', 'language')},
        ),
        migrations.CreateModel(
            name='BibleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=20)),
                ('book', models.CharField(max_length=60)),
                ('book_number', models.PositiveSmallIntegerField(db_index=True)),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['version', 'book_number'], name='songs_bible_version_8e5b1f_idx')],
                'unique_together': {('version', 'book_number', 'chapter', 'verse')},
            },
        ),
    ]
