# Generated by Django 5.2 on 2026-09-29 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0155_quiz_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=64)),
                ('language', models.CharField(default='en', max_length=5)),
                ('kind', models.CharField(max_length=12)),
                ('difficulty', models.CharField(max_length=10)),
                ('category', models.CharField(blank=True, default='', max_length=20)),
                ('prompt', models.TextField()),
                ('passage', models.TextField(blank=True, default='')),
                ('choices', models.JSONField(default=list)),
                ('answer_index', models.PositiveSmallIntegerField()),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('explanation', models.TextField(blank=True, default='')),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('due_on', models.DateField(db_index=True)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='songs.bankquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='review_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asks', to='songs.reviewitem'),
        ),
        migrations.AddIndex(
            model_name='reviewitem',
            index=models.Index(fields=['user', 'mastered_at', 'due_on'], name='songs_revie_user_id_0d9169_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewitem',
            unique_together={('user', 'source_key')},
        ),
    ]
