# Generated by Django 5.2 on 2026-09-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0156_spaced_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='hint_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coinspend',
            name='reason',
            field=models.CharField(choices=[('hint', 'Puzzle hint'), ('freeze', 'Streak freeze'), ('quiz_hint', 'Quiz 50/50')], default='hint', max_length=20),
        ),
    ]
