# Generated by Django 5.2 on 2026-09-29 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0157_quiz_hints'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='duel_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duels', to='songs.quizsession'),
        ),
    ]
