# Generated by Django 5.2 on 2026-09-29 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0158_quiz_duels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=80)),
                ('language', models.CharField(default='en', max_length=5)),
                ('seconds', models.PositiveSmallIntegerField(default=20)),
                ('status', models.CharField(choices=[('lobby', 'Waiting to start'), ('question', 'Question open'), ('reveal', 'Answer shown'), ('finished', 'Finished')], db_index=True, default='lobby', max_length=10)),
                ('current', models.SmallIntegerField(default=-1)),
                ('question_started_at', models.DateTimeField(blank=True, null=True)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_battles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BattlePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveSmallIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='songs.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points', '-correct', 'joined_at'],
                'unique_together': {('battle', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BattleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(max_length=12)),
                ('difficulty', models.CharField(max_length=10)),
                ('prompt', models.TextField()),
                ('passage', models.TextField(blank=True, default='')),
                ('choices', models.JSONField(default=list)),
                ('answer_index', models.PositiveSmallIntegerField()),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('explanation', models.TextField(blank=True, default='')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='songs.battle')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('battle', 'order')},
            },
        ),
        migrations.CreateModel(
            name='BattleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.SmallIntegerField(null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('points', models.PositiveIntegerField(default=0)),
                ('ms', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='songs.battleplayer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='songs.battlequestion')),
            ],
            options={
                'unique_together': {('player', 'question')},
            },
        ),
    ]
