# Generated by Django 5.2 on 2026-09-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0159_bible_battles'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzleprogress',
            name='letters_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='puzzleprogress',
            name='shown',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='coinspend',
            name='reason',
            field=models.CharField(choices=[('hint', 'Puzzle hint'), ('letter', 'Puzzle letter'), ('freeze', 'Streak freeze'), ('quiz_hint', 'Quiz 50/50')], default='hint', max_length=20),
        ),
    ]
