# Generated by Django 5.2 on 2026-09-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0160_puzzle_letters'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordpuzzle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wordpuzzle',
            name='day',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='wordpuzzle',
            constraint=models.UniqueConstraint(condition=models.Q(('day__isnull', True)), fields=('theme', 'level'), name='puzzle_one_per_theme_level'),
        ),
        migrations.AddConstraint(
            model_name='wordpuzzle',
            constraint=models.UniqueConstraint(condition=models.Q(('day__isnull', False)), fields=('day',), name='puzzle_one_a_day'),
        ),
    ]
