# Generated by Django 5.2 on 2026-09-29 20:37

import django.db.models.deletion
from django.db import migrations, models

# The seeded themes in Swahili. A topic theme also gets the word searched for
# in the Swahili Bible: "omba" finds kuomba, aliomba, maombi.
SWAHILI = {
    'books-of-the-law': ('Vitabu vya Sheria', 'Vitabu vitano vya kwanza vya Biblia.', None),
    'the-gospels': ('Injili', 'Mathayo, Marko, Luka na Yohana.', None),
    'the-prophets': ('Manabii', 'Isaya hadi Malaki.', None),
    'psalm-23': ('Zaburi 23', 'Bwana ndiye mchungaji wangu.', None),
    'creation': ('Uumbaji', 'Sura ya kwanza ya Mwanzo.', None),
    'the-beatitudes': ('Heri', 'Mahubiri ya mlimani, Mathayo 5.', None),
    'proverbs-wisdom': ('Mithali', 'Hekima, kutoka kitabu cha Mithali.', None),
    'faith': ('Imani', 'Maneno kutoka mistari inayozungumzia imani.', 'imani'),
    'love': ('Upendo', 'Maneno kutoka mistari inayozungumzia upendo.', 'upendo'),
    'prayer': ('Maombi', 'Maneno kutoka mistari inayozungumzia maombi.', 'omba'),
}


def name_in_swahili(apps, schema_editor):
    PuzzleTheme = apps.get_model('songs', 'PuzzleTheme')
    for theme in PuzzleTheme.objects.filter(slug__in=SWAHILI):
        name, description, term = SWAHILI[theme.slug]
        theme.name_sw, theme.description_sw = name, description
        if term:
            theme.source = {**(theme.source or {}), 'term_sw': term}
        theme.save(update_fields=['name_sw', 'description_sw', 'source'])


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0162_puzzle_challenges'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wordpuzzle',
            name='puzzle_one_per_theme_level',
        ),
        migrations.RemoveConstraint(
            model_name='wordpuzzle',
            name='puzzle_one_a_day',
        ),
        migrations.RemoveIndex(
            model_name='bibleword',
            name='songs_bible_length_33e0df_idx',
        ),
        migrations.AddField(
            model_name='bibleword',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='puzzletheme',
            name='description_sw',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='puzzletheme',
            name='name_sw',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='wordpuzzle',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='wordpuzzle',
            name='sw_verse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='songs.bibletext'),
        ),
        migrations.AlterField(
            model_name='bibleword',
            name='word',
            field=models.CharField(max_length=24),
        ),
        migrations.AddIndex(
            model_name='bibleword',
            index=models.Index(fields=['language', 'length', '-frequency'], name='songs_bible_languag_8a7c25_idx'),
        ),
        migrations.AddConstraint(
            model_name='bibleword',
            constraint=models.UniqueConstraint(fields=('language', 'word'), name='bibleword_one_per_language'),
        ),
        migrations.AddConstraint(
            model_name='wordpuzzle',
            constraint=models.UniqueConstraint(condition=models.Q(('day__isnull', True)), fields=('theme', 'level', 'language'), name='puzzle_one_per_theme_level_language'),
        ),
        migrations.AddConstraint(
            model_name='wordpuzzle',
            constraint=models.UniqueConstraint(condition=models.Q(('day__isnull', False)), fields=('day', 'language'), name='puzzle_one_a_day_per_language'),
        ),
        migrations.RunPython(name_in_swahili, migrations.RunPython.noop),
    ]
