# Generated by Django 5.2 on 2026-09-30 05:22

from django.db import migrations, models


def remember_what_was_bought(apps, schema_editor):
    """Existing order lines get their product's title and currency now, while
    the products are still there. (Pictures are read from the product while
    it lasts; new orders keep their own.)"""
    OrderItem = apps.get_model('songs', 'OrderItem')
    for item in OrderItem.objects.filter(product__isnull=False).select_related('product').iterator():
        item.title = (item.product.title or '')[:200]
        item.currency = item.product.currency or 'USD'
        item.save(update_fields=['title', 'currency'])


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0163_puzzle_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.RunPython(remember_what_was_bought, migrations.RunPython.noop),
    ]
