# Generated by Django 5.2 on 2026-09-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0165_market_orders_sellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='quiet_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='quiet_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='utc_offset',
            field=models.SmallIntegerField(default=180),
        ),
    ]
