# Generated by Django 5.2 on 2026-10-01 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def tidy(apps, schema_editor):
    """The audit trail keeps who acted by name; and Django's staff flag is
    taken from everyone who is not a super admin (demotions used to leave it,
    and it opened staff-only doors)."""
    User = apps.get_model('songs', 'User')
    Log = apps.get_model('songs', 'AdminActionLog')
    for entry in Log.objects.filter(actor__isnull=False).select_related('actor').iterator():
        entry.actor_name = entry.actor.username
        entry.save(update_fields=['actor_name'])
    (User.objects.filter(is_staff=True, is_superuser=False)
     .exclude(admin_role='super_admin').update(is_staff=False))


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0168_major_market_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('verified_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=60)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminTwoFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_encrypted', models.TextField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_step', models.BigIntegerField(default=0)),
                ('backup_hashes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='actor_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='entry_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='prev_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['target_type', 'target_id'], name='songs_admin_target__2f0149_idx'),
        ),
        migrations.AddField(
            model_name='adminsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admintwofactor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_two_factor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['user', 'expires_at'], name='songs_admin_user_id_60023d_idx'),
        ),
        migrations.RunPython(tidy, migrations.RunPython.noop),
    ]
