# Generated by Django 5.2 on 2026-10-02 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0170_app_settings_broadcasts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('man', 'Man'), ('woman', 'Woman')], max_length=8)),
                ('country', models.CharField(max_length=60)),
                ('town', models.CharField(blank=True, default='', max_length=80)),
                ('church', models.CharField(blank=True, default='', max_length=120)),
                ('baptised', models.CharField(choices=[('yes', 'Yes'), ('not_yet', 'Not yet')], max_length=8)),
                ('looking_for', models.CharField(choices=[('marriage', 'Marriage'), ('friendship', 'Friendship that may lead to marriage')], default='marriage', max_length=12)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('about', models.TextField(blank=True, default='', max_length=500)),
                ('prompts', models.JSONField(blank=True, default=list)),
                ('occupation', models.CharField(blank=True, default='', max_length=80)),
                ('education', models.CharField(blank=True, default='', max_length=80)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Waiting for review'), ('approved', 'Approved'), ('rejected', 'Changes needed'), ('banned', 'Banned')], default='draft', max_length=10)),
                ('review_note', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('agreed_rules_at', models.DateTimeField()),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='singles_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='singles_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SinglesPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Waiting for review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='songs.singlesprofile')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='singlesprofile',
            index=models.Index(fields=['status', 'gender', 'is_paused'], name='songs_singl_status_204a64_idx'),
        ),
    ]
