# Generated by Django 5.2 on 2026-10-02 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0171_singles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglesInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('interested', 'Interested'), ('pass', 'Not now')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_given', to='songs.singlesprofile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_received', to='songs.singlesprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['from_profile', 'created_at'], name='songs_singl_from_pr_6574fe_idx'), models.Index(fields=['to_profile', 'kind'], name='songs_singl_to_prof_2e6e15_idx')],
                'unique_together': {('from_profile', 'to_profile')},
            },
        ),
        migrations.CreateModel(
            name='SinglesMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='singles_match', to='songs.conversation')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='songs.singlesprofile')),
                ('profile_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='songs.singlesprofile')),
            ],
            options={
                'unique_together': {('profile_a', 'profile_b')},
            },
        ),
    ]
