# Generated by Django 5.2 on 2026-10-02 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0172_singles_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='livebroadcast',
            name='singles_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singlesprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlesprofile',
            name='diet',
            field=models.CharField(blank=True, choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('flexible', 'Flexible'), ('', 'Not said')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='singlesprofile',
            name='discoverable',
            field=models.CharField(choices=[('everyone', 'Everyone eligible'), ('liked', 'Only people I am interested in')], default='everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='singlesprofile',
            name='ministries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='singlesprofile',
            name='photo_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlesprofile',
            name='pref_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='singlesprofile',
            name='pref_intents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='singlesprofile',
            name='pref_max_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlesprofile',
            name='pref_min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlesprofile',
            name='show_age',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='singlesprofile',
            name='show_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='singlesprofile',
            name='show_town',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Voice note'), ('verse', 'Scripture')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='singlesprofile',
            name='looking_for',
            field=models.CharField(choices=[('open', 'Open to meeting people'), ('friendship', 'Friendship first'), ('serious', 'Serious relationship'), ('marriage', 'Marriage-minded')], default='marriage', max_length=12),
        ),
        migrations.CreateModel(
            name='SinglesGathering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('coffee', 'Coffee meet-up'), ('bible_study', 'Bible study'), ('outdoors', 'Outdoors'), ('concert', 'Concert'), ('retreat', 'Retreat'), ('seminar', 'Seminar'), ('prayer', 'Prayer evening'), ('online', 'Online meet & greet')], max_length=16)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='', max_length=1500)),
                ('starts_at', models.DateTimeField()),
                ('place', models.CharField(blank=True, default='', max_length=160)),
                ('country', models.CharField(blank=True, default='', max_length=60)),
                ('online', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Waiting for review'), ('approved', 'Listed'), ('rejected', 'Not listed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('review_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singles_gatherings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='SinglesIcebreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('answers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icebreakers', to='songs.singlesmatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SinglesStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(max_length=3000)),
                ('photo', models.CharField(blank=True, default='', max_length=500)),
                ('consents', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('published', 'Published'), ('rejected', 'Not published')], default='pending', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='songs.singlesmatch')),
            ],
        ),
        migrations.CreateModel(
            name='SinglesTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('heart_count', models.PositiveIntegerField(default=0)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='songs.singlesprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SinglesReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=600)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='songs.singlesprofile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='songs.singlestopic')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SinglesVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfie', models.CharField(max_length=500)),
                ('gesture', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('approved', 'Verified'), ('rejected', 'Not verified')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='songs.singlesprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SinglesAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('answer', models.CharField(max_length=40)),
                ('visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='songs.singlesprofile')),
            ],
            options={
                'unique_together': {('profile', 'key')},
            },
        ),
        migrations.CreateModel(
            name='SinglesRsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='songs.singlesgathering')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='songs.singlesprofile')),
            ],
            options={
                'unique_together': {('gathering', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='SinglesSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='songs.singlesprofile')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='songs.singlesprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'created_at'], name='songs_singl_kind_0f9b11_idx'), models.Index(fields=['target', 'kind'], name='songs_singl_target__cff763_idx')],
            },
        ),
        migrations.CreateModel(
            name='SinglesHeart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='songs.singlesprofile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearts', to='songs.singlestopic')),
            ],
            options={
                'unique_together': {('topic', 'profile')},
            },
        ),
    ]
