# Generated by Django 5.2 on 2026-10-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0173_singles_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='livebroadcast',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
