# Generated by Django 5.2 on 2026-10-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0174_takedown_orgs_clubs_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
