# Generated by Django 5.2 on 2026-10-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0176_story_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
