# Generated by Django 5.2 on 2026-10-07 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0178_profile_identity_pinned_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('title_sw', models.CharField(blank=True, default='', max_length=80)),
                ('summary', models.CharField(blank=True, default='', max_length=200)),
                ('summary_sw', models.CharField(blank=True, default='', max_length=200)),
                ('book_number', models.PositiveSmallIntegerField()),
                ('chapter_start', models.PositiveSmallIntegerField()),
                ('chapter_end', models.PositiveSmallIntegerField()),
                ('icon', models.CharField(blank=True, default='book-outline', max_length=40)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='calibrated_from',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='origin',
            field=models.CharField(choices=[('written', 'Written by a person'), ('ai', 'Drafted by Claude')], default='written', max_length=8),
        ),
        migrations.AddField(
            model_name='dailyquiz',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='topic',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='kind',
            field=models.CharField(choices=[('book', 'Which book'), ('blank', 'Missing word'), ('reference', 'Which reference'), ('section', 'Which chapters'), ('order', 'Which comes first'), ('finish', 'Finish the verse'), ('exact', 'Quoted exactly?'), ('who_said', 'Who said this'), ('true_false', 'True or false'), ('fact', 'Bible fact')], max_length=12),
        ),
        migrations.CreateModel(
            name='DailyQuizStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('play_started_at', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starts', to='songs.dailyquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_starts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quiz')},
            },
        ),
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, default='', max_length=12)),
                ('language', models.CharField(default='en', max_length=5)),
                ('prompt', models.TextField()),
                ('passage', models.TextField(blank=True, default='')),
                ('choices', models.JSONField(default=list)),
                ('answer_index', models.PositiveSmallIntegerField(default=0)),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('reason', models.CharField(choices=[('wrong_answer', 'The marked answer is wrong'), ('unclear', 'Unclear or ambiguous'), ('typo', 'Spelling or text error'), ('other', 'Something else')], max_length=14)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fixed', 'Fixed'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='songs.bankquestion')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='songs.quizquestion')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('question__isnull', False)), fields=('user', 'question'), name='questionreport_once_per_user')],
            },
        ),
    ]
