# Generated by Django 5.2 on 2026-10-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0180_quiz_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='app_prefs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='language',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
