# Generated by Django 5.2 on 2026-10-07 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0181_app_prefs_and_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=80)),
                ('platform', models.CharField(blank=True, default='', max_length=10)),
                ('app_version', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
