# Generated by Django 5.2 on 2026-10-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0182_session_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment or Bullying'), ('hate', 'Hate Speech'), ('violence', 'Violence or Threats'), ('sexual', 'Sexual Content'), ('child_safety', 'Child Safety'), ('self_harm', 'Self-harm or Suicide'), ('scam', 'Scam or Fraud'), ('impersonation', 'Impersonation'), ('inappropriate', 'Inappropriate Content'), ('misinformation', 'Misinformation'), ('copyright', 'Copyright Violation'), ('other', 'Other')], max_length=20),
        ),
    ]
