# Generated by Django 5.2 on 2026-10-07 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0184_ban_details_mass_takedown'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=64, unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('automatic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('password_guessing', 'Password guessing on one account'), ('credential_stuffing', 'Many accounts tried from one address'), ('signup_burst', 'Many sign-ups from one address'), ('ban_evasion', 'A banned person may be back'), ('rate_limit_spike', 'Many requests refused for going too fast'), ('account_takeover', 'Someone says a sign-in was not them')], max_length=24)),
                ('severity', models.CharField(default='medium', max_length=8)),
                ('ip', models.CharField(blank=True, default='', max_length=45)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip', models.CharField(blank=True, db_index=True, default='', max_length=45)),
                ('outcome', models.CharField(default='ok', max_length=16)),
                ('device_name', models.CharField(blank=True, default='', max_length=80)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip', '-created_at'], name='songs_login_ip_a32920_idx'), models.Index(fields=['username', '-created_at'], name='songs_login_usernam_4e9771_idx')],
            },
        ),
    ]
