# Generated by Django 5.2 on 2026-10-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0186_recovery_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohostrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('left', 'Left'), ('removed', 'Removed')], default='pending', max_length=10),
        ),
    ]
