# Generated by Django 5.2 on 2026-10-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0187_cohost_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='livebroadcast',
            name='muted_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='livebroadcast',
            name='pinned',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
