# Generated by Django 5.2 on 2026-10-10 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0189_search_trigram_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to='songs.product'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to='songs.videostudio'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('book', 'Book'), ('product', 'Product'), ('service', 'Service')], max_length=10),
        ),
    ]
