# Generated by Django 5.2 on 2026-10-10 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


PACKAGES = [
    # key, name, KES, views, days
    ('starter', 'Starter', 200, 1000, 3),
    ('standard', 'Standard', 500, 3000, 5),
    ('plus', 'Plus', 1000, 7000, 7),
]


def seed(apps, schema_editor):
    Package = apps.get_model('songs', 'PromotionPackage')
    for i, (key, name, price, views, days) in enumerate(PACKAGES):
        Package.objects.get_or_create(key=key, defaults=dict(name=name, price=price, views=views, days=days, order=i))


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0190_feed_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('price', models.PositiveIntegerField(help_text='KES')),
                ('views', models.PositiveIntegerField(help_text='Views promised')),
                ('days', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('post', 'Post'), ('profile', 'Profile'), ('product', 'Product'), ('book', 'Book'), ('service', 'Service')], max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('views_target', models.PositiveIntegerField()),
                ('days', models.PositiveSmallIntegerField()),
                ('counties', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paying', 'Paying'), ('review', 'Review'), ('active', 'Active'), ('done', 'Done'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='unpaid', max_length=10)),
                ('payment_reference', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('payment_phone', models.CharField(blank=True, max_length=12)),
                ('payment_note', models.CharField(blank=True, max_length=255)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('refund_due', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('follows', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='songs.socialpost')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='songs.product')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='songs.publication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='songs.videostudio')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='songs.promotionpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('clicked', models.BooleanField(default=False)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by', to='songs.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['status', 'ends_at'], name='songs_promo_status_4f57db_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotionview',
            constraint=models.UniqueConstraint(fields=('promotion', 'user', 'day'), name='promotionview_once_a_day'),
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
