# Generated by Django 5.2 on 2026-10-10 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0191_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='songs.socialpost'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='songs.product'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='songs.publication'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='songs.videostudio'),
        ),
    ]
