# Generated by Django 5.2 on 2026-10-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0192_promotion_keep_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotionpackage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paying', 'Paying'), ('review', 'Review'), ('active', 'Active'), ('paused', 'Paused'), ('done', 'Done'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='unpaid', max_length=10),
        ),
    ]
